version: '3'
services:
    my-sql:
        image: mysql:5.7
        container_name: coe-mysql
        volumes:
            - mysql-data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: coe_db
            MYSQL_USER: coe_user
            MYSQL_PASSWORD: coe_password
        ports:
            - 3306:3306
        networks:
            - default
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    web:
        build: .
        image: coe-image
        container_name: coe-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9000:9000
        links:
            - my-sql
        networks:
            - default
        restart: always
        environment:
            COE_SETTINGS: /app/.env
        command:
          /venv/bin/gunicorn -w 4 --bind 0.0.0.0:9000 "coe.web:create_app()"
        logging:
            options:
                max-size: "10m"
                max-file: "3"